# WHERE IS THE PROJECT COMING
FROM node:14.17

# SET WORKING DIRECTORY
WORKDIR /app

# COPY PACKAGE MENIFEST TO WORKDIR (.)
COPY package.json .

# AFTER COPYING MANIFEST NOW INSTALL PACKAGES
RUN npm install

# COPY ALL-FIELS TO WORKING DIRECTORY (. .)

COPY . .

# START THE SERVER
CMD npm run start:dev
